MidwestFurryFandom/rams

- uber/site_sections/preregistration.py
These emails weren't actually getting rendered.
> Add format flag for Dealer html emails

- uber/templates/static_views/slow_load.html
> Fixed static magfest ref to static furfest ref

- Dockerfile
- uber/common.py
- uber/configspec.ini
- uber/decorators.py
- uber/models.py
- uber/site_sections/accounts.py
- uber/templates/base.html
- uber/templates/static_views/slow_load.html
- uber/utils.py
Pull in the latest from staging for the art_show launch
> Mff staging

- uber/model_checks.py
- uber/models.py
- uber/utils.py
Deploy that fix for dots being pulled from emails (Silly magtern, dots are essential).
Fixes #164
> Email Dot Fix

- uber/config.py
- uber/models.py
- uber/templates/registration/form.html
- uber/templates/registration/new_base.html
Changes here fix bugs exposed by art_show and elsewhere. Fixes there will rely on these changes to function properly.
> Badge pricing and numbering fixes

- uber/config.py
- uber/models.py
- uber/site_sections/registration.py
- uber/templates/regform.html
- uber/templates/registration/arbitrary_charge_form.html
- uber/templates/registration/index_base.html
- uber/templates/registration/new_base.html
- uber/templates/registration/register.html
Bug fixes focused on the on-site registration process
> Merge staging

- uber/templates/preregistration/preregbase.html
Fixes https://github.com/MidwestFurryFandom/mff-rams-plugin/issues/47
> Make Attending badge type box change the badge type

- uber/site_sections/schedule.py
- uber/templates/groups/form.html
Fixes https://github.com/MidwestFurryFandom/mff-rams-plugin/issues/59.
> Stop rendering 'email' textarea for new dealers

- uber/site_sections/preregistration.py
- uber/templates/preregistration/confirm.html
Fixes https://github.com/MidwestFurryFandom/mff-rams-plugin/issues/50.
> Hide "attractions" tab if no attractions are public yet

- uber/automated_emails.py
Fixes https://github.com/MidwestFurryFandom/mff-rams-plugin/issues/35.
> Require approval for default Dealer payment reminder emails

- uber/model_checks.py
- uber/templates/macros.html
- uber/templates/preregistration/group_members.html
Fixes https://github.com/MidwestFurryFandom/mff-rams-plugin/issues/65 (part 2).
> Stop model-checking admin changes to dealers

- uber/site_sections/mivs_judging.py
- uber/site_sections/preregistration.py
Fixes https://github.com/MidwestFurryFandom/mff-rams-plugin/issues/76.
> Use from:c.ADMIN_EMAIL for emails to departments

- uber/templates/preregistration/preregbase.html
Fixes https://github.com/MidwestFurryFandom/mff-rams-plugin/issues/48.
> Only reset badge to attendee/group if applicable

- uber/templates/macros.html
Adds a macro for a generic Bootstrap-based button radio group.
> Add "button" style radio group

- uber/templates/macros.html
> Update name_form_group macro for Art Show

- requirements.txt
> Add FPDF to requirements.txt

- uber/config.py
Fixes https://github.com/MidwestFurryFandom/rams/issues/279
> Move MFF badge stock checks to mff-rams-plugin

- uber/templates/preregistration/preregbase.html
- uber/templates/regform.html
- uber/templates/registration/index_base.html
Fixes https://github.com/MidwestFurryFandom/mff-rams-plugin/issues/133.
> Fix badge level buttons for badge type prices after a price increase

- uber/configspec.ini
- uber/site_sections/registration.py
Allows us to fix https://github.com/MidwestFurryFandom/mff-rams-plugin/issues/132 by configuring the various messages to be what we want. The group message is not included in this change since we plan to remove that feature.
> Make at-door messages configurable

- uber/models/group.py
- uber/templates/groupform.html
- uber/templates/preregistration/group_members.html
We had a couple bugs and UI issues for our dealer badge limits, so this handles that so MFF can actually use those limits.
> Fix dynamic dealer badge limit

- uber/automated_emails.py
How did this file not make it into the last commit? It is a mystery.
> Actually remove the waitlist exhausted email this time

- uber/templates/static_views/prereg_not_yet_open.html
Since we're looking at launching at maybe a midday time, let's show that time.
> Added time of day

- uber/templates/regform.html
Fixes https://github.com/MidwestFurryFandom/rams/issues/319.
> Mark full address as required

- uber/templates/regform.html
Fixes https://github.com/MidwestFurryFandom/rams/issues/329.
> Only show kick-in tier expiry message if there were ever kick-in tiers

- uber/templates/fields/attendee.html
Fixes https://github.com/MidwestFurryFandom/rams/issues/343 by making fields appear as expected according to the Javascript in mff-rams-plugin.
> Fix Javascript errors and remove extra merch fields

- uber/models/attendee.py
This will help us override this presave adjustments in the mff plugin.
> Split "Staffing Adjustments" presave adjustments

- alembic/versions/e0c620d341cb_add_cost_tracking_and_registered_date_.py
Acheron is experiencing an error about this while trying to set up a new development environment -- this should hopefully fix it.
> Force 523e3d243395 to depend on promo code group migration

- uber/config.py
- uber/templates/check_in.html
- uber/templates/registration/check_in_form_base.html
We found a couple last-minute bugs while testing. This includes the fixes for them, plus a minor performance improvement.
> Fix JS bugs in modal check-in form

- uber/site_sections/preregistration.py
- uber/templates/emails/reg_workflow/attendee_qrcode.html
Small text changes and (hopefully) one last bugfix before launch.
> Last minute fixes (core repo)

- uber/menu.py
- uber/models/__init__.py
- uber/site_sections/preregistration.py
- uber/site_sections/reg_admin.py
- uber/templates/reg_admin/orphaned_attendees.html
Fixes https://github.com/MidwestFurryFandom/rams/issues/432.
> Don't delete accounts that have valid attendees

- uber/tasks/email.py
Fixes https://github.com/MidwestFurryFandom/rams/issues/435.
This is already running in prod using the feature branch, we just need to merge it to make it permanent.
> Fix 500 error on email error logging

- uber/templates/art_show_admin/pieces_bought.html
Found this while testing at-con operations for art show.
> Fix template errors for art show sales page

- uber/templates/emails/art_show/mailing_in.html
Fixes https://github.com/MidwestFurryFandom/rams/issues/466.
> Updating mailing-in instruction emails

- uber/api.py
Pushing this out for testing with the print server.
> Add basic API method for pulling printable attendees

- uber/api.py
- uber/models/__init__.py
- uber/site_sections/badge_printing.py
Also updates the other endpoints to more properly return errors. Also renames them to be a bit more consistent with other endpoints.
> Add API endpoint for queueing badges

- uber/models/art_show.py
Fixes https://github.com/MidwestFurryFandom/rams/issues/484.
> Call random.choices correctly

- uber/templates/base.html
Found this while testing. It MIGHT be the cause of the page sometimes not loading for Staff badges.
> Fix some error messages breaking JS

- uber/menu.py
- uber/site_sections/art_show_admin.py
- uber/site_sections/art_show_applications.py
- uber/site_sections/art_show_reports.py
- uber/templates/art_show_admin/bidder_signup.html
- uber/templates/art_show_admin/pieces_bought.html
- uber/templates/art_show_admin/sales_search.html
- uber/templates/art_show_common/art_pieces_form.html
- uber/templates/art_show_common/artist_checkin_macros.html
- uber/templates/art_show_common/print_macros.html
- uber/utils.py
Also includes a few very easy non-must-have issues. Note that some of these require extra testing in staging, which I'll do after it's deployed to staging.
> Fix all must-have art show issues

- uber/templates/fields/attendee.html
- uber/templates/registration/attendee_data.html
- uber/templates/registration/form.html
Fixes https://github.com/MidwestFurryFandom/rams/issues/443.
> Add account data to attendee form

- uber/models/__init__.py
- uber/models/types.py
Fixes a bug that made badges not correctly save ribbon_labels when being queued to print.
> Fix missing ribbon labels

- uber/models/art_show.py
The art show admin index page isn't showing a piece count for certain artists because we're calculating a couple properties too naively. This should fix that.
> Fix issues preventing pieces from being listed for some artists

- uber/models/attendee.py
Fixes https://github.com/MidwestFurryFandom/rams/issues/499.
> Stop setting badge_num to None pre-con

- uber/templates/art_show_admin/artist_check_in_out.html
- uber/templates/art_show_common/artist_checkin_macros.html
Fixes https://github.com/MidwestFurryFandom/rams/issues/456, for real this time. Also includes some display improvements, like forcing the General/Mature buttons to be on one line.
> Fix artist check-in modal

- uber/site_sections/art_show_reports.py
Fixes https://github.com/MidwestFurryFandom/rams/issues/496.
> Fix attendee-less art apps for artist_csv

- development-defaults.ini
- uber/api.py
- uber/config.py
- uber/models/__init__.py
- uber/site_sections/badge_printing.py
- uber/site_sections/landing.py
- uber/site_sections/preregistration.py
- uber/site_sections/registration.py
- uber/templates/badge_printing/queue_badge.html
- uber/templates/fields/attendee.html
- uber/templates/landing/index.html
- uber/templates/preregistration/create_or_login_account.html
- uber/templates/preregistration/form.html
- uber/templates/preregistration/login.html
- uber/templates/registration/attendee_pending_warning.html
- uber/templates/registration/check_in_form_base.html
- uber/templates/registration/form.html
- uber/templates/registration/index_base.html
- uber/templates/registration/minor_check_form.html
- uber/templates/registration/pay.html
- uber/templates/registration/register.html
A slew of UI updates and bug fixes for at-con mode. The most important change is to enable accounts for at-con mode and add a flag that lets you put a station into 'kiosk mode' to prevent people from logging into their accounts.
> Updates for at-con mode and badge printing

- uber/sep_commands.py
I'm not 100% sure this will work, but it's worth a shot since it's unclear what the problem is in the code that's producing duplicate badge number errors.
> Try to ignore errors while resaving attendees

- uber/automated_emails.py
We want to eliminate any reason the emails we want to send aren't sending because I do not fucking have time for this
> Make emails easier to send

- uber/site_sections/art_show_admin.py
- uber/templates/art_show_admin/pieces_bought.html
We still can't figure out where the bad number is coming from, but this should fix it better.
> Fix the integer error some more

- uber/api.py
Part of fixing https://jira.furfest.org/browse/SEI_SW-60. We'll want to test these with import functions before calling them final.
> Add API calls for exporting attendee accounts

- uber/api.py
- uber/configspec.ini
- uber/utils.py
There was a bug in the way we called other servers' API services from inside the system. Also adds an 'all' option for attendee account export.
> Fix page handler API calls

- uber/config.py
Hopefully this won't clash with https://github.com/MidwestFurryFandom/rams/pull/549 -- if it does, let me know and I'll merge it manually.
> Allow plugins to have integer_enums

- uber/api.py
(Hopefully) finishes the changes needed to let us export attendees from the prior year. Doesn't include any of the importing stuff yet.
> Add group exporting

- requirements.txt
- uber/configspec.ini
- uber/model_checks.py
- uber/site_sections/accounts.py
- uber/site_sections/mivs_admin.py
- uber/templates/emails/accounts/new_account.txt
- uber/utils.py
Admins can now log in using their MFF Auth0 account.
> Add Auth0 SSO for admin accounts

- uber/configspec.ini
- uber/site_sections/statistics.py
This feature had issues last year that required hard-coding for MAGFest, so it's now off by default so as to make the server work again.
> Add ability to turn off broken maps feature

- alembic/versions/acbafbe2c23e_add_current_attendees_to_track_imported_.py
- uber/configspec.ini
- uber/custom_tags.py
- uber/models/__init__.py
- uber/models/attendee.py
- uber/site_sections/art_show_applications.py
- uber/site_sections/marketplace.py
- uber/site_sections/preregistration.py
- uber/templates/preregistration/attendee_card.html
- uber/templates/preregistration/form.html
- uber/templates/preregistration/homepage.html
- uber/templates/preregistration/update_account.html
This should help clean up some bugs and just generally be more convenient for people. Also adds a database relationship to tie imported badges to the badges people repurchase or reapply with.
> Overhaul attendee homepage and add reapply for dealers

- uber/config.py
- uber/configspec.ini
Fixes what was effectively a typo in calling some functions
> Fix AWS secret fetching error

- uber/api.py
- uber/models/__init__.py
I realized while wrapping up account importing that we couldn't import MFF-only fields -- this adds support for that.
> Add importing support for plugin fields

- uber/receipt_items.py
Found this error on staging even though I definitely tested viewing dealer groups before merging.
> Fix 500 error when viewing dealers

- uber/models/__init__.py
- uber/models/attendee.py
- uber/models/commerce.py
- uber/models/group.py
- uber/templates/fields/attendee.html
We need this fix in order to be able to save groups on the admin side. Also fixes an issue where fully refunding an attendee didn't actually add a refund transaction.
> Fix hybrid properties for payments

- uber/templates/preregistration/confirm.html
- uber/templates/registration/index_base.html
- uber/utils.py
Also makes it extra-clear if you're viewing an invalid registration that it is not, in fact, valid.
> Handle importing staff attendee accounts

- uber/templates/fields/attendee.html
- uber/templates/preregistration/attendee_card.html
- uber/templates/preregistration/homepage.html
Fixes https://github.com/MidwestFurryFandom/rams/issues/570. Fixes https://github.com/MidwestFurryFandom/rams/issues/571.
> Prereg Fixes (round 1)

- uber/models/__init__.py
- uber/templates/emails/accounts/new_account.txt
One last fix for dealer reg, hopefully.
> Add missing / to admin account email

- uber/templates/preregistration/confirm.html
> Stop dealers buying their badges

- uber/config.py
- uber/models/__init__.py
- uber/models/attendee.py
- uber/site_sections/art_show_admin.py
- uber/site_sections/art_show_applications.py
- uber/site_sections/group_admin.py
- uber/site_sections/preregistration.py
- uber/site_sections/reg_admin.py
- uber/templates/fields/attendee.html
- uber/templates/preregistration/badge_updated.html
- uber/templates/preregistration/confirm.html
- uber/templates/preregistration/homepage.html
- uber/templates/preregistration/new_badge_payment.html
- uber/templates/preregistration/receipt_table.html
- uber/templates/preregistration/upgrade_modal.html
- uber/templates/reg_admin/receipt_items.html
- uber/utils.py
Also fixes https://github.com/MidwestFurryFandom/rams/issues/588 and a handful of other payment-related bugs.
> Let new attendees pay on their confirmation page

- uber/site_sections/preregistration.py
- uber/templates/fields/group.html
- uber/utils.py
Converts group payment to the new system so dealers can actually pay for their approved groups. Also fixes the group cost breakdown on the group page.
> Fix process_group_payment

- uber/config.py
- uber/custom_tags.py
- uber/models/attendee.py
- uber/models/commerce.py
- uber/models/legal.py
- uber/receipt_items.py
- uber/site_sections/preregistration.py
- uber/templates/fields/attendee.html
- uber/templates/fields/group.html
- uber/templates/preregistration/confirm.html
- uber/templates/registration/form.html
Also fixes a 500 error in cases where the server can't retrieve a SignNow document, and includes a workaround for an odd issue where the list of regions wasn't always being included on the group management page.
> Allow dealers to upgrade badges

- uber/config.py
- uber/model_checks.py
- uber/models/__init__.py
- uber/models/attendee.py
- uber/models/commerce.py
- uber/receipt_items.py
- uber/site_sections/art_show_applications.py
- uber/site_sections/badge_printing.py
- uber/site_sections/dept_checklist.py
- uber/site_sections/marketplace.py
- uber/site_sections/preregistration.py
- uber/site_sections/reg_admin.py
- uber/site_sections/registration.py
- uber/site_sections/shifts_admin.py
- uber/templates/base.html
- uber/templates/confirm_tabs.html
- uber/templates/fields/attendee.html
- uber/templates/marketplace/edit.html
- uber/templates/preregistration/confirm.html
- uber/templates/preregistration/form.html
- uber/templates/preregistration/group_members.html
- uber/templates/preregistration/index.html
- uber/templates/preregistration/receipt_table.html
- uber/templates/preregistration/stripeForm.html
- uber/templates/preregistration/upgrade_modal.html
- uber/templates/reg_admin/receipt_items.html
- uber/utils.py
Pulls in fixes for some things we don't need but several things we do need.
> Pull Receipt Items fixes from MAGFest

- uber/models/group.py
- uber/receipt_items.py
- uber/site_sections/preregistration.py
- uber/templates/fields/group.html
- uber/templates/preregistration/group_members.html
Fixes a bug with custom group costs, and lets groups resume pending payments.
> Group payment fixes

- uber/models/__init__.py
- uber/models/commerce.py
- uber/site_sections/preregistration.py
- uber/site_sections/reg_admin.py
- uber/templates/reg_admin/import_attendees.html
- uber/templates/reg_admin/receipt_items.html
- uber/templates/registration/attendee_data.html
- uber/utils.py
We found several issues on MAGFest's side with the refactoring and fixing we did earlier. This fixes those and a few other minor things that likely won't come up for MFF.
> Pull in fixes from MAGFest for the fixes from MAGFest

- uber/site_sections/reg_admin.py
- uber/templates/reg_admin/attendees_who_owe_money.html
- uber/templates/reg_admin/receipt_items.html
We want to see who owes money and also has an upgraded badge, so we need this sooner rather than later.
> Fix unpaid attendee report

- uber/templates/emails/art_show/mailing_in.html
- uber/templates/emails/art_show/pieces_reminder.txt
> Update Art Show emails

- script_example.py
This will give future-me a jumping off point for writing scripts to run against the DB for special cases.
> Add example script

- uber/models/__init__.py
- uber/models/attendee.py
- uber/site_sections/registration.py
Allows you to search more columns, adds the ability to search with >, <, >=, <=, and != operands, and improves error handling for unsearchable properties.
I did this as part of trying to add properties to the search so we could more easily find not-fully-paid attendees, but I ran into performance issues and stopped before going too far down the rabbit-hole.
> Improve attribute search

- uber/models/__init__.py
I mixed up which way the alligator was facing.
> Switch <= and >= operators

- uber/site_sections/preregistration.py
I can't really test this because the first fix worked on my machine, but based on the error message we're seeing this should hopefully take care of things.
> Fix comped groups adding badges, again

- uber/site_sections/art_show_admin.py
- uber/site_sections/reg_admin.py
- uber/templates/art_show_admin/assign_locations.html
- uber/templates/art_show_admin/form.html
- uber/templates/art_show_admin/history.html
- uber/templates/art_show_admin/pieces.html
- uber/templates/art_show_common/artist_checkin_macros.html
- uber/templates/art_show_common/print_form.html
- uber/templates/art_show_common/print_macros.html
- uber/templates/reg_admin/receipt_items.html
- Fixes payment button for art show receipts
- Fixes 'assign locations' page
- Improves spacing for printing artist check-in forms
> Implement fixes for at-con art show operations

- uber/site_sections/dealer_admin.py
- uber/site_sections/preregistration.py
Fixes the "Decline and Convert" button
> Fix converting declined dealers

- uber/automated_emails.py
- uber/models/__init__.py
- uber/models/art_show.py
- uber/models/attendee.py
- uber/models/group.py
- uber/site_sections/art_show_applications.py
- uber/site_sections/reg_admin.py
- uber/site_sections/registration.py
- uber/templates/art_show_admin/index.html
- uber/templates/art_show_applications/edit.html
- uber/templates/fields/attendee.html
- uber/templates/reg_admin/attendee_account_form.html
- uber/templates/reg_admin/orphaned_attendees.html
- uber/templates/registration/form.html
- uber/templates/registration/reg_take_report.html
We need this to go to prod so that the art show bugs are fixed.
> Improve account management and fix art show bugs

- uber/models/__init__.py
- uber/models/commerce.py
- uber/site_sections/art_show_admin.py
- uber/site_sections/art_show_applications.py
- uber/site_sections/group_admin.py
- uber/site_sections/preregistration.py
- uber/site_sections/registration.py
A couple of the changes I'd made -- specifically the receipt auto-updater and the refreshing of receipts/attendees on load -- actually broke admins' ability to create new badges. Blithe needs these fixes ASAP tomorrow.
> Fix errors with adding new attendees

- uber/models/commerce.py
Somehow this was broken even though I definitely tested this while working on it.
> Fix last_incomplete_txn

- uber/templates/art_show_admin/artist_check_in_out.html
Adds a safety check so the artist check-in modal stops spitting out an error
> Fix datatable reinitialization error

- uber/configspec.ini
- uber/model_checks.py
- uber/site_sections/preregistration.py
- uber/templates/macros.html
- uber/templates/preregistration/create_or_login_account.html
- uber/templates/preregistration/form.html
- uber/templates/preregistration/group_members.html
- uber/templates/preregistration/index.html
- uber/templates/preregistration/login.html
- uber/templates/preregistration/stripeForm.html
- uber/templates/reg_admin/receipt_items.html
- uber/utils.py
Fixes https://jira.furfest.org/browse/SEI_SW-97 by checking Stripe for the status of pending payments and resuming the attendee where they left off. Also fixes https://jira.furfest.org/browse/SEI_SW-164. Also fixes some other bugs introduced by either the bootstrap upgrade or the merge from MAGFest.
> Simplify prereg workflow

- requirements.txt
- uber/config.py
- uber/configspec.ini
- uber/models/__init__.py
- uber/site_sections/accounts.py
- uber/site_sections/landing.py
- uber/site_sections/saml.py
- uber/templates/emails/accounts/new_account.txt
- uber/templates/landing/index.html
- uber/templates/landing/login_select.html
- uber/utils.py
Implements a basic version of SAML login for both admin and attendee accounts. There are several implementation details to figure out still. Fixes most of https://jira.furfest.org/browse/SEI_SW-163.
> Migrate from OAuth to SAML login

- uber/config.py
Will fix the 500 error on server startup. Whoops!
> Remove reference to auth0_secret

- uber/payments.py
- uber/utils.py
> Remove more authlib references

- uber/configspec.ini
- uber/decorators.py
- uber/models/__init__.py
- uber/models/commerce.py
- uber/payments.py
- uber/receipt_items.py
- uber/site_sections/preregistration.py
- uber/site_sections/reg_admin.py
- uber/templates/base.html
- uber/templates/forms/README.md
- uber/templates/forms/badge_extras.html
- uber/templates/forms/consents.html
- uber/templates/forms/macros.html
- uber/templates/forms/other_info.html
- uber/templates/forms/personal_info.html
- uber/templates/preregistration/attendee_card.html
- uber/templates/preregistration/homepage.html
- uber/templates/preregistration/login_or_create_account.html
- uber/templates/reg_admin/receipt_items.html
Fixes the following issues from the first round of QA (https://wiki.furfest.org/pages/viewpage.action?spaceKey=REG&title=2023+QA):
1. "-" characters are now allowed in passwords
2. Account creation now creates accounts with passwords that you can then use to log into the account
3. "Forgot password" link is now always visible
4. Attendee homepage is now slightly less of a disaster
5. You can access your homepage from the "badge updated" page
6. Fields are now shown in a single column on mobile devices
7. Logging out of your attendee account now clears all prereg cart data
Also manually re-implements https://github.com/magfest/ubersystem/commit/53b05612d85993061c35a501488b96f4b45c8106 so merging will be slightly less obnoxious (it is going to be very obnoxious).
> Prereg fixes round 1

- uber/decorators.py
- uber/forms/attendee.py
- uber/site_sections/preregistration.py
- uber/templates/landing/index.html
- uber/utils.py
- uber/validations/attendee.py
- uber/validations/group.py
Fixes several bugs that prevented you from filing a dealer application, all of which I somehow introduced after testing dealer applications.
> Fix blocking bugs for dealer reg testing

- uber/payments.py
- uber/receipt_items.py
- uber/site_sections/art_show_applications.py
- uber/site_sections/registration.py
- uber/templates/art_show_applications/confirmation.html
- uber/templates/art_show_applications/edit.html
- uber/templates/art_show_applications/index.html
- uber/templates/base.html
- uber/templates/confirm_tabs.html
- uber/templates/marketplace/edit.html
- uber/templates/marketplace/index.html
- uber/templates/preregistration/preregbase.html
- uber/templates/preregistration/stripeForm.html
This mostly involves making all the shared pages compatible with bootstrap 3. I had also accidentally removed all the fields for creating a new badge.
Also includes unapproved dealers in the attendee search.
> Get art show applications working

- alembic/versions/459045b27a25_add_replyto_for_emails.py
- uber/amazon_ses.py
- uber/automated_emails.py
- uber/models/email.py
- uber/tasks/email.py
- uber/templates/emails/art_show/appchange_notification.html
Adds the ability to specifiy a replyto address for emails sent from the system.
> Add replyto for automated emails

- Dockerfile
- requirements.txt
Going to switch to a feature branch for staging until I get this figured out
> Blind attempt to fix our Dockerfile

- uber/tasks/redis.py
This was a basic wrong function call.
> Fix 500 error in update_problem_names

- uber/models/attendee.py
- uber/site_sections/hotel_lottery.py
- uber/templates/hotel_lottery/room_group.html
- uber/templates/hotel_lottery/terms.html
Adds a quick link to join any hotel lottery room groups that are controlled by the currently logged-in account -- this should help people form room groups much more easily, especially if they're dealers.
> Add faster room group joining

- uber/templates/forms/macros.html
- uber/templates/preregistration/attendee_card.html
- uber/templates/preregistration/homepage.html
These seem to have never been added. Also adds the confirmation number to attendee cards on the homepage.
> Add validation messages for card selects

- uber/templates/preregistration/homepage.html
That would have been: a problem
> Don't say hotel lottery is open when it's not

- uber/templates/forms/hotel/suite_lottery.html
- uber/validations/attendee.py
- uber/validations/hotel_lottery.py
Fixes and updates for the staff hotel lottery.
> Staff hotel lottery 2025

- uber/models/hotel.py
- uber/templates/preregistration/homepage.html
- uber/utils.py
- uber/validations/hotel_lottery.py
Updates the date display on the homepage to handle cases where both the staff and hotel lottery are open. Also adds a validation to prevent people from entering the hotel lottery if they won't be 21 by the time they check in.
> Attendee hotel lottery updates

- uber/site_sections/hotel_lottery_admin.py
- uber/site_sections/reg_admin.py
- uber/templates/hotel_lottery_admin/index.html
- uber/templates/preregistration/group_add_members.html
- uber/templates/reg_admin/attendee_accounts.html
- uber/templates/reg_admin/automated_transactions.html
- uber/templates/registration/index_base.html
Also updates the hotel export of countries, and allows dealers to attach existing registrations to their group before being approved.
> Add attendee account server-side pagination

- uber/config.py
- uber/tasks/email.py
Somehow this didn't get included in the commit. I have no idea how.
> Actually fix the email signature

- uber/tasks/email.py
> Re-remove reconcile fixtures on startup
