MidwestFurryFandom/rams

uber/config.py, uber/configspec.ini, uber/models.py, uber/templates/preregistration/form.html, uber/templates/preregistration/preregbase.html, uber/templates/regform.html
Fixes https://github.com/MidwestFurryFandom/rams/issues/1. Fixes https://github.com/MidwestFurryFandom/rams/issues/2. Fixes https://github.com/MidwestFurryFandom/rams/issues/3. Fixes https://github.com/MidwestFurryFandom/rams/issues/4. Does all this by adding and integrating a new config option badge types called badge_type_prices. Adding badge types to this option puts them on the pre-reg and confirmation pages as attendee-facing badge types. Unlike the attendee badge, however, their price is fixed and cannot change.
=> Add configurable attendee-facing badge types, with set prices

uber/configspec.ini, uber/models.py, uber/site_sections/preregistration.py, uber/templates/preregistration/repurchase.html, uber/templates/regform.html
Fixes https://github.com/MidwestFurryFandom/rams/issues/13. When an attendee visits the confirmation page of a Refunded badge, they will be given the option to buy a new badge. Their information is transferred over. Also fixes a couple JS bugs, and stops the system detecting Refunded and Deferred badges as duplicates (because those badges are not valid for checking in).
=> Allow attendees to repurchase refunded badges

uber/configspec.ini, uber/templates/base.html
Attempts to fix what I believe is the cause of https://github.com/MidwestFurryFandom/rams/issues/155 by allowing events to disable the "Slow Loading" page. The config option is set to true by default to avoid surprising events that depend on this page being in use.
=> Add an option to disable the 'slow loading' page

uber/utils.py
Fixes #167 
While so far we have only seen stripe errors, because this is a catch-all fn for serious errors, this has been limited to the ADMIN_EMAIL
=> Removed dom's email

uber/utils.py
We inherited the use of cached_property for several properties in the Charge class when we hand-updated the class to MAGFest's version. However, there are now some issues with these properties, likely because MAGFest uses a newer version of Sideboard that updates cached_property. This should (hopefully) fix a couple bugs with sending data over to Stripe.
=> Remove use of cached_property in Charge class

uber/site_sections/registration.py
This is impossible to test because of the way the Stripe testing keys work, but it shouuuuld be solid. This fixes the problem we had when a card went to Stripe and was then declined, bringing admins to a page that triggered a 500 error.
=> Fix 500 error when a card is declined

uber/configspec.ini, uber/models/promo_code.py
Even if a promo code gave a badge no discount, it would display as a "free badge." Also fixes a 500 error caused by missing config.
=> Allow for promo codes without a discount

uber/templates/groupform.html
mff-rams-plugin relies on this ID existing in order to hide this text. It was likely removed by accident when we merged from MAGFest, so we're adding it back.
=> Add #moretables back to group form template

uber/templates/preregistration/group_members.html
Wording on instructions for group members was awkward. Now it is less so.
fixes #245
=> Update group member wording

uber/templates/base.html
This adds the ability to generate filters for any datatable-enabled column on any page by simply adding a span with the ID of "[lowercase table heading]_filter" to the page. The code in base.html will then generate a dropdown using the data in that column. The end result is a dynamic list of unique options to filter the table by.
Uses a modified version of https://datatables.net/manual/api#Example---column-filter
=> Add ability to automatically filter any DataTable column

uber/static/deps/selectToAutocomplete/index.html
fixes #260 
Confession: Best-guess on the characters based on some wikipedia reading. Pretty sure it says "Taiwan" now, but it might not say enough. Hard to tell. Ask Kofu.
=> Removed ref to China from Taiwan

uber/templates/preregistration/group_members.html
Fixes https://github.com/MidwestFurryFandom/rams/issues/244. For some reason we were using `is_transferable` as a proxy for telling if the group leader can drop someone's badge. We already have `can_abandon_badge` to see if someone can remove their own badge, so now we just use that.
=> Allow group leaders to drop non-transferable group members

uber/models/group.py, uber/site_sections/groups.py, uber/templates/groups/form.html
This does two things: ALWAYS show dealer fields if a group has categories, and count a group as a dealer if they have any status besides Unapproved. This should help fix https://github.com/MidwestFurryFandom/rams/issues/259 without breaking everything unexpectedly.
=> Show dealer fields and support free dealers in certain circumstances

uber/templates/macros.html
This lets us specify the maximum length of an input field.
=> Add maxlength as an option for the form_group macro

uber/model_checks.py, uber/models/attendee.py, uber/site_sections/preregistration.py, uber/templates/preregistration/confirm.html
Our art show app needs to redirect people to the art show app page when they have an unpaid app. This PR adds a variable into the main system so we can change it in the plugin.
=> Add support for an alternate payment page

uber/templates/base.html
When we used the $('#id') syntax, any unusual characters in the text of a header would trip up jQuery. We change it to the functionally-equivalent $(*[id="id"]) syntax so we can escape the header name, letting us have anything we want for a header name.
=> Escape th names to prevent jQuery errors in DataTable tables

uber/templates/macros.html
For unknown reasons, running regionChange() on page load was not actually changing the dropdown box inside the artist check-in model. This supports the fix for that.
=> Force address form state to refresh on artist check-in modals

uber/config.py
We hadn't caught this for MAGFest yet because neither MAGWest nor MAGStock meet the conditions to run the affected line.
=> Fix Badge Range assignment

uber/models/group.py
Using the event plugin to override a hybrid property doesn't actually work (and it's not clear it ever did), so we're moving this into the main plugin. It should be safe to change it.
=> Move changes to is_dealer expression back to main plugin

uber/templates/macros.html
Our radio buttons were misaligned on our forms, so they needed an extra class to get back in line.
=> Fix radiobutton group alignment in forms

uber/templates/emails/dealers/waitlist_closing.txt
We haven't sent this email in at least two years that I can tell. Admins get notifications that it hasn't been approved -- removing it is the only way to stop that.
=> Remove old one-off "Waitlist Exhausted" email

uber/model_checks.py, uber/site_sections/preregistration.py, uber/templates/groupform.html
Fixes https://github.com/MidwestFurryFandom/rams/issues/320 -- if someone was submitting the form as a group or dealer, we were accidentally resetting the variable that stores validation error messages. Also fixes a bug where the dealer address fields weren't actually being copied into the group leader's address fields, and adds validation for emergency contact numbers, which previously could be empty if the attendee was from outside the US.
=> Fix dealer registration validation and handling

uber/utils.py
Fixes https://github.com/MidwestFurryFandom/rams/issues/327. Also fixes a related bug where group transactions were erroneously treated as promo-code (i.e., attendee) group transactions.
=> Fix Stripe descriptions for attendees

uber/site_sections/preregistration.py, uber/templates/groupform.html
We weren't properly storing the 'badges' selection between page loads, so any validation error would reset it to 1. This is now fixed so dealers won't accidentally submit the form with just one badge when they wanted more.
=> Don't reset # of badges when throwing validation errors for dealers

uber/templates/regform.html
Address form will now only be required if admin_area is false.
=> Made address form admin-aware, #335

uber/templates/fields/attendee.html
The fact that this box said 'volunteering' was confusing, so now it says if the attendee is staffing or volunteering.
=> Use "volunteering" and "staffing" on admin form

uber/model_checks.py, uber/models/attendee.py
We have a few flags that end up setting `staffing` to true for attendees, but our model checks would miss these soon-to-be-staff. This fixes that.
=> Add staffing_or_will_be for use in model checks

uber/api.py, uber/models/__init__.py, uber/models/attendee.py, uber/models/types.py, uber/site_sections/import.py
Fixes https://github.com/MidwestFurryFandom/rams/issues/306. This includes a lot of upgrades to the custom database types that we have. Any type that we define in this system can now accept strings as inputs, including strings of labels instead of the underlying special integer values. I couldn't do this to the UTCDateTime, Date, or Boolean columns, so we process those values inside the API instead.
You can update basically any field, as far as I know. Some types of fields have not gotten the special treatment that allows you to use their names instead of IDs -- for example, if you wish to update someone's assigned departments, you'll need to set their `assigned_depts_ids` to a comma-separated list of the UUIDs of departments, not their names. You can retrieve the IDs using the existing …
=> Add create and update functions for Attendees to the API

uber/templates/registration/register.html
=> Add missing badge name field to on-site registration form

alembic/versions/e0c620d341cb_add_cost_tracking_and_registered_date_.py
This reverts commit c875fd0d9fec6e5d3aeb891d38816ef73972b017.
It was blowing up staging, alas. Migrations are not great.
=> Revert "Force 523e3d243395 to depend on promo code group migration"

uber/models/attendee.py, uber/site_sections/registration.py, uber/templates/check_in.html, uber/templates/registration/check_in_form_base.html
The at-door page is super slow, so it's better to just be able to mark an attendee as paid after searching for them in /registration/index. This adds an alternate version of the checkin dialogue that lets you mark them as paid or process a stripe payment for their registration.
Once an attendee is marked as paid, the check-in modal seamlessly reloads to show the check-in form.
=> Add payment workflow to prereg checkin

uber/configspec.ini, uber/templates/base.html
The paper airplane in the admin area was hard-coded to use MAGFest's JIRA. It's now configurable, and set to not show by default.
=> Make JIRA feedback button configurable

development-defaults.ini, uber/site_sections/registration.py, uber/templates/base.html, uber/templates/check_in.html, uber/templates/fields/attendee.html, uber/templates/registration/check_in_form_base.html, uber/templates/registration/form.html, uber/templates/registration/index_base.html
Fixes https://github.com/MidwestFurryFandom/rams/issues/310. Fixes https://github.com/MidwestFurryFandom/rams/issues/312. Also includes some visual updates, and a fix for the attendee form showing the wrong payment options in at-con mode.
During the event (i.e., `at_the_con` is True), if an attendee has an amount unpaid, we now show a Stripe button at the top of their Details page:
Note that for cash payments, you can enter the payment method and set the "paid" box in their usual place near the bottom of the form:
If the attendee can be checked in, we show a "Save & Check In" button at the bottom of their page:
After checking someone in, you are redirected back to the search page:
The form also detects if saving the attendee makes them unable to check in!
=> Add check-in and payment buttons to attendee details page

uber/templates/registration/index_base.html
We no longer need this, and it's a huge hit to the system so we shouldn't tempt people with it.
=> Remove button to load "At-Door Registrations" page

development-defaults.ini
Reg asked for this to be removed to speed up at-door check-ins. Note that this only removes the option for attendees; reg volunteers can still process Stripe payments at the door.
=> Turn off "Pay with credit card at the registration desk" option

uber/automated_emails.py
By default almost all emails are locked down when we're at the con, since many stop being relevant. People should still receive their QR codes, though.
=> Send QR code email when in at-con mode

alembic/versions/e0c620d341cb_add_cost_tracking_and_registered_date_.py
Reverts MidwestFurryFandom/rams#362
We now need this change again for spinning up new instances. Just... don't touch prod from 2019.
=> Revert "Revert "Force 523e3d243395 to depend on promo code group migration""

uber/templates/fields/attendee.html
Fixes a fairly large set of issues displaying badges when different badge types were sold out. Most importantly, people who view their page when their existing badge type is sold out will not be automatically upgraded to the next type.
This does NOT fix a handful of edge cases around people who are in the middle of buying badges when a badge type is sold out, as that was out of scope and the default behavior of the app is to just silently give people Attendee badges. There is also one edge case where if a Sponsor cancels an upgrade while Sponsor badges are sold out they cannot downgrade -- the correct behavior needs to be decided on.
Lastly, new attendees whose payments are pending do not count against badge stocks, but existing attendees whose upgrading payments are pending do count …
=> Stop automatically upgrading badges when sold out

uber/models/__init__.py, uber/site_sections/art_show_applications.py, uber/site_sections/marketplace.py, uber/site_sections/preregistration.py, uber/site_sections/reg_admin.py, uber/templates/art_show_applications/edit.html, uber/templates/confirm_tabs.html, uber/templates/marketplace/edit.html, uber/templates/preregistration/confirm.html, uber/templates/preregistration/group_members.html, uber/templates/preregistration/group_promo_codes.html, uber/templates/preregistration/homepage.html, uber/templates/preregistration/preregbase.html, uber/templates/preregistration/update_account.html
There were a few regressions introduced recently around logged-in accounts. This fixes that, plus it fixes a minor bug with admins viewing attendee pages and (hopefully) makes the attendee accounts admin page efficient enough to use.
Fixes https://github.com/MidwestFurryFandom/rams/issues/402. Fixes https://github.com/MidwestFurryFandom/rams/issues/403.
=> Fix logged-in accounts

uber/site_sections/preregistration.py, uber/utils.py
Fixes https://github.com/MidwestFurryFandom/rams/issues/430. If we send the email during the payment page handler, the email gets sent before the webhook has a chance to actually mark the dealer as paid. Now we'll only send it when the dealer is counted as paid.
=> Send dealer paid email via payment webhook

uber/automated_emails.py, uber/models/attendee.py, uber/site_sections/preregistration.py, uber/site_sections/reg_admin.py, uber/templates/emails/accounts/new_account.html, uber/templates/reg_admin/orphaned_attendees.html
Also updates the orphaned attendees list to be a little more useful. Also, holds back account confirmation emails if someone hasn't finished setting up their new account yet.
=> Let admins create new accounts for orphaned attendees

uber/models/__init__.py
We set num_event_shirts to default to -1, which is supposed to represent an unselected choice, but that was causing an error when trying to access its label. We now special-case -1  -- which would only be set explicitly in code for Choice columns -- to return a default "Unknown" label.
=> Fix num_event_shirts_label 500 error

uber/models/art_show.py, uber/site_sections/art_show_applications.py, uber/templates/preregistration/confirm.html
Fixes https://github.com/MidwestFurryFandom/rams/issues/450. Fixes https://github.com/MidwestFurryFandom/rams/issues/463. Also fixes a previously undiscovered bug that redirected artists to a 404 error after saving their application.
=> Fix high-priority Art Show errors

uber/automated_emails.py
We were only sending emails to art show apps that have a status of c.PAID, but that was refactored out earlier.
=> Fix art show email prerequisites

uber/templates/fields/attendee.html, uber/templates/registration/attendee_data.html, uber/templates/registration/form.html
You could only create placeholder attendees via the modal because the DOB field wasn't being included. This fixes that. Also cleans up the reprint_fee field a bit so it's properly integrated, adds the 'legal name' checkbox for admins to reduce confusion, and removes the at-con payment warning if you're creating a new attendee.
=> Fix attendee creation via modal

uber/models/art_show.py
We were redefining the incomplete_reason inside mff-rams-plugin, but there's no longer a reason for the main and mff plugin to treat art show apps differently, so this merges them to make code maintenance easier.
=> Merge art show incomplete_reason to main plugin

uber/templates/preregistration/preregbase.html
Admins were getting shown these buttons when viewing attendee data. That's confusing, so now we check to at least make sure they're logged into an attendee account.
=> Hide homepage and logout buttons if not logged in

uber/templates/base.html, uber/utils.py
While working on the badge printing I figured out how to make multiple errors properly appear in toastr message pop-ups. This doesn't fix every case, but now the check() function will return more than one error at a time, greatly improving UX when filling out forms.
=> Improve toastr error messages

alembic/versions/40ec91ad7a74_add_print_queue_table.py, uber/api.py, uber/models/__init__.py, uber/models/admin.py, uber/models/attendee.py, uber/models/badge_printing.py, uber/site_sections/badge_printing.py, uber/site_sections/registration.py, uber/templates/api/reference.html, uber/templates/badge_printing/queued_badges.html, uber/templates/registration/form.html, uber/templates/registration/queue_badge.html
This is the first major step of adding support for a printer server (https://github.com/MidwestFurryFandom/rams/issues/460). It includes the API endpoints and enough front-end changes for basic testing.
To test, browse to /registration/ and set your Reg Station number using the button toggle near the top:
Then open any reasonably-complete Attendee's form, enter any string for the printer ID, and click "Queue for Printing":
You can see print jobs using the new page at /badge_printing/queued_badges. Browse to /api/reference and find the "Print Job Service" section to test the API endpoints.
=> Add PrintJob table and API

uber/api.py, uber/models/__init__.py, uber/templates/badge_printing/queued_badges.html
This should finish the API for print jobs, barring anything found in testing. Includes more metadata in pending_jobs, the ability to select jobs by printer_id, some improvements to print_job_error and print_job_complete, and an update call that runs if restart is passed to pending_jobs.
=> Add metadata to print job API

uber/templates/fields/attendee.html
Fixes https://github.com/MidwestFurryFandom/rams/issues/458. We were only rendering the printed name field on the admin form in certain cases -- now we just keep it hidden under those same cases, so the MFF plugin can unhide it like it does with attendee-facing pages.
=> Always render badge printed name field

uber/site_sections/preregistration.py
Part of fixing https://github.com/MidwestFurryFandom/rams/issues/465. Without this change, approved dealers updating their groups would run into errors about having no address set.
=> Only change group address if it's present

uber/models/attendee.py
Fixes https://github.com/MidwestFurryFandom/rams/issues/372 -- the check we use for sending the QR code email is the same as the check we use for people who can check in, so this should prevent any non-approved dealers from getting this email.
=> Mark unapproved dealers as not ready to check in

uber/api.py, uber/models/__init__.py, uber/models/attendee.py, uber/site_sections/devtools.py
Fixes the following issues:
- not actually checking for duplicate attendee name+email (debug values were left in)
- blowing up when given empty strings for some fields (we now skip any empty fields)
- blowing up on JSONB fields (we now parse them in MagModel.apply)
- model checks blowing up when labels were given instead of literal Choice/MultiChoice values (we now also parse labels in MagModel.apply, not just when actually saving to the DB)
- two bugs in Attendee.total_cost, one where an exception wasn't being thrown correctly and another where amount_extra is set to None by MagModel.apply and then the total_cost property expects it to always be an integer, again blowing up model checks
=> Fix several bugs with API attendee creation

uber/models/__init__.py, uber/site_sections/badge_printing.py, uber/site_sections/registration.py, uber/templates/badge_printing/print_jobs.html, uber/templates/badge_printing/queued_badges.html, uber/templates/check_in.html, uber/templates/fields/attendee.html, uber/templates/group_admin/form.html, uber/templates/registration/check_in_form_base.html, uber/templates/registration/index_base.html, uber/templates/registration/minor_check_form.html, uber/templates/registration/printer_id_form.html
The second half of https://github.com/MidwestFurryFandom/rams/issues/460. Adds a set of modals that guide admins through setting their default printer and minor printer IDs, printing badges, and switching out badge stock if they're printing minor badges on their default printer.
Here's the basic workflow:
1. The admin browses to People > Attendees, searches for an attendee by first name/last name (or even better, QR code) then clicks the green Check In button seen here: 
2. A modal pops up prompting the admin for a reg station number (note: MUST be an integer), a default printer ID, and a default printer ID for attendees under 18. These values are per-session and the reg station number should be unique to each check-in station: 
3. After entering this information, the admin is presented …
=> Add workflow for printing badges during check-in

uber/templates/emails/accounts/new_account.txt
This email was linking to the base URL, which redirects to the landing page, which has a login form for ATTENDEE accounts. Linking directly to the admin section of the system should help reduce confusion.
=> Update confusing login link for new admins

uber/models/__init__.py
The system keeps redirecting admins to an "invalid badge" page inappropriately anytime I forget to specify allow_invalid=True, so now we just check to see if they're a logged in admin before redirecting someone.
=> Let admins see invalid badges

uber/templates/registration/check_in_form_base.html
An HTML error was preventing the printer ID to be passed through in some cases. 😬
=> Fix print button for attendees without preset badge numbers

uber/site_sections/registration.py, uber/templates/registration/index_base.html
The index page only shows check-in buttons for unpaid attendees if the Reg Station # is set. However, for events with badge printing, the reg station # gets set inside the check-in modal. To make things less confusing, we now just display the check-in button for unpaid attendees from the start.
=> Enable check-in buttons for unpaid attendees

uber/templates/registration/attendee_pending_warning.html, uber/templates/registration/check_in_form_base.html
Because of how aynchronous calls work, when an admin takes a payment through Stripe, the check-in modal loads too soon to see that the attendee has been marked paid. Now we hide the alert when loading the check-in modal from the payment modal -- if something truly went wrong with the payment, the attendee will still be prevented from checking in, and if that's the case you'll need manager intervention anyway.
=> Hide payment alert if you literally just took payment

uber/sep_commands.py
Fixes an issue where, if you ran into an error while resaving all attendees in the system, no attendee would actually get updated.
=> Make resave_all_attendees_and_groups atomic

uber/templates/art_show_admin/assign_locations.html
The general/mature grid table headers are backwards on this page! This fixes that.
=> Switch headers for assign locations page

uber/model_checks.py
We were filtering by badge type while checking for numbers, but this means we would hit a DB error an awful lot. Now we just look for the same badge number, not the same badge type.
=> Catch duplicate badge numbers better

uber/site_sections/registration.py
If you search by badge number, you get redirected to the attendee's form even in at the con mode. This seems like something we might not want.
=> Never redirect to attendee page at-con

uber/site_sections/art_show_admin.py
It's disconcerting that we don't know why this is happening, but this should least stop the error that's preventing card payment.
=> Bypass int casting error

uber/site_sections/art_show_admin.py
The query for closing out art show pieces is too inclusive -- this will make it match the one we use for sales.
=> Improve piece search for closeout

uber/configspec.ini, uber/templates/fields/group.html, uber/templates/macros.html, uber/templates/preregistration/group_members.html
Adds a new config value "approved_dealer_editable_fields," which lets you set certain group fields that dealers will be able to edit after being approved.
=> Add optional fields approved dealers can edit

uber/api.py
Apparently we had NEVER been importing attendees' legal names... whoops. We also need their address, and their account IDs to make sure their accounts are always imported with them.
=> Add missing fields to attendee/group import

uber/config.py, uber/configspec.ini, uber/models/legal.py, uber/site_sections/preregistration.py, uber/templates/fields/group.html, uber/templates/preregistration/group_members.html, uber/utils.py
Also moves the AWS secret fetching into the main plugin for easier integration with page handlers.
I have no idea how to test this on my local system, but I wanted to file the PR before I forgot.
=> Switch to access token for SignNow

uber/templates/fields/attendee.html, uber/templates/group_admin/form.html
The merge from MAGFest caused the dealer prereg form to misbehave, prompting you to select a badge type when you shouldn't be able to. Also adds a background to the dealer admin form because I was sick of looking at it.
=> Fix dealer prereg form

uber/configspec.ini, uber/models/legal.py, uber/utils.py
We were redirecting people to the literal string "%(url_base)". Now we just use the redirect URL only if it's actually set. Also actually uses the redirect URL for the signnow integration.
=> Fix redirect URL

uber/models/legal.py, uber/site_sections/preregistration.py, uber/utils.py
If a dealer completed signing the T&C but our app never got the redirect callback, we would ask them to sign the T&C but give them a broken link. Now we fetch the document from SignNow and check that it isn't already signed before we ask them to sign it.
=> Avoid giving dealers expired signing links

uber/utils.py
We were redirecting to the domain name + /rams/rams/accounts, this fixes that.
=> Remove extra 'rams' from redirect URI

uber/config.py, uber/models/group.py, uber/models/legal.py, uber/site_sections/preregistration.py, uber/utils.py
Includes all the final stuff we need for the terms and conditions, like prefilling in certain fields. Also fixes a bug if a dealer happened to not have a T&C document created at all when they applied.
=> Finalize SignNow dealer T&C document

uber/api.py, uber/automated_emails.py, uber/badge_funcs.py, uber/models/attendee.py, uber/sep_commands.py, uber/templates/base.html, uber/templates/emails/reg_workflow/account_confirmation.html, uber/templates/group_admin/dealers.html, uber/templates/group_admin/guests.html, uber/templates/group_admin/index.html, uber/templates/group_admin/mivs.html, uber/utils.py
A handful of miscellaneous fixes for importing:
- Prevent 'account confirmed' emails from sending to imported accounts
- Stop imported badges from being assigned badge numbers
- List only valid attendees in account confirmation emails
- Add panel backing to group list view
- Hide imported dealers from dealer list by default
=> Final fixes for importing dealers

uber/models/__init__.py
You can now retrieve a model's default cost via the calculation in receipt items. This allows us to, e.g., tell dealers what their costs will be in an email. Since these cost properties can ONLY accurately calculate the cost of something for an unpaid model, we log an error if they're called on a model with an active receipt.
=> Add ability to access costs as a property

uber/amazon_ses.py, uber/configspec.ini
It turns out our secrets manager and email sending service do NOT use the same region. Also adds some ~more logging~
=> Fix AWS region for emails

uber/templates/emails/dealer_resend_confirmation.html, uber/templates/fields/group.html
Also prevents dealers from signing their T&C for now. This change is meant to be reversed later.
=> Add extra dealer email

uber/config.py
get_badge_count_by_type returns a value while inside a new SQLAlchemy session, which causes problems with DB connection pool usage. This should fix that.
I have not tested whether this fixes the db connection pool issues, but I'm filing the PR now in case we need it in an emergency.
=> Close the session in get_badge_count_by_type

uber/utils.py
We weren't properly processing groups' badge prices and were always only adding the cost of a single badge.
=> Fix group badge cost

uber/tasks/registration.py
Importing 1000 attendee accounts takes about 20 minutes, so we're bumping up the interval of API queue processing to avoid clashes.
=> Set API queue processing to once every half-hour

uber/custom_tags.py
We're not sure how, but someone ended up with an invalid number on their registration and now they can't see their homepage because phonenumbers throws an Exception. We now effectively bypass that exception, since this is purely for display purposes.
=> Avoid crashing the template for invalid phone numbers

uber/models/attendee.py, uber/templates/preregistration/index.html
While fixing child badge registration I noticed that the system was calling any discounted badge free. This fixes that. Also includes a fix for undo_extra for non-MFF events.
=> Don't call all child badges free

uber/site_sections/api.py, uber/utils.py
The Stripe webhook handler had a bug in it that should have caused it to always fail. How did we not notice this??
I have limited ability to test this locally, so this should be tested on staging.
=> Fix Stripe webhook handler

uber/models/__init__.py, uber/models/art_show.py, uber/models/attendee.py, uber/models/group.py, uber/receipt_items.py, uber/templates/art_show_applications/edit.html, uber/templates/emails/dealers/approved.html
Fixes a bug where sometimes an attendee or art show application's cost would be displayed as cents rather than in dollars. We're keeping most costs/fees as dollars for now since in some cases admins are able to edit these directly and I don't feel like doing a ton of input conversions.
Also fixes issues with dealer's default costs not being calculated correctly.
=> Better standardize dollars vs cents values

uber/receipt_items.py, uber/templates/preregistration/index.html
The default_badge_cost property doesn't actually take age discounts into account, which is by design, so now we have to check the age discount inside the template.
=> Fix "attendees who are X get in free!" message

uber/config.py, uber/utils.py
If you had a SignNow dealer document ID set, but no secret name for SignNow set, you couldn't view any dealers without a 500 error. This adds safety checks and error messages to better handle that.
=> Handle bad SignNow secrets config

uber/site_sections/preregistration.py
Fixes a bug where a comped group (i.e. one without a receipt) couldn't actually buy extra badges.
=> Let groups without receipts buy badges

uber/templates/schedule/edit.html
The schedule page has been showing twice as many slots as it should since at least 2017. How did we miss this??
=> Fix a 5-year-old bug in the schedule page

alembic/versions/fa2deb095760_add_column_to_track_email_sending.py, uber/models/email.py, uber/tasks/email.py
Email sending is now done every 15 minutes instead of ever 5 minutes, unless you're on a development box. The email sending task now also locks all the active email categories while it processes them.
=> Fix automated emails double-sending

uber/models/__init__.py, uber/models/art_show.py, uber/models/attendee.py, uber/models/commerce.py, uber/models/group.py, uber/receipt_items.py, uber/site_sections/art_show_admin.py, uber/site_sections/art_show_applications.py, uber/site_sections/attractions.py, uber/site_sections/badge_printing.py, uber/site_sections/group_admin.py, uber/site_sections/preregistration.py, uber/site_sections/reg_admin.py, uber/site_sections/registration.py, uber/templates/badge_printing/queue_badge.html, uber/templates/fields/attendee.html, uber/templates/fields/group.html, uber/templates/model_history_base.html, uber/templates/preregistration/group_members.html, uber/templates/preregistration/group_promo_codes.html, uber/templates/reg_admin/receipt_items.html, uber/templates/registration/at_door_complete.html, uber/templates/registration/check_in_form_base.html, uber/templates/registration/index_base.html, uber/utils.py
🤞 🤞 🤞 
Includes the following:
- Improves UX of receipt items page, including a history tab for each receipt
- Automatically updates existing receipts for groups, attendees, and art show applications based on admin changes
- Ignores receipts for invalid attendees and groups
- Adds badge reprint fees to receipts when a badge print is queued, and adds a credit if badge print is invalidated
- Adds explicit badge confirmation page for at-door registrations -- this page is skipped in kiosk mode
- Fixes various display bugs for the at-con registration page, check-in modal, admin form, and group management page
=> Add features and bug fixes required at-event

uber/site_sections/art_show_applications.py, uber/site_sections/preregistration.py
Fixes a bug where attendees, groups, and apps without receipts would generate a 500 error on the attendee side when viewing their respective pages.
=> Fix issue with viewing receiptless attendees

uber/templates/preregistration/homepage.html
Fixes an issue where people would just be told prereg was closed when they logged in.
=> Account for at-con on attendee homepage

uber/models/__init__.py, uber/models/attendee.py, uber/models/group.py, uber/site_sections/registration.py, uber/utils.py
Includes the following:
- Fixes a bug where attendees with pending payments weren't marked as paid even when they had paid up
- Creates receipts for attendees when they first register at-door, so those receipts can be edited if needed
- Stops Stripe refund error messages
=> At-con payment fixes

uber/models/__init__.py, uber/models/group.py, uber/site_sections/preregistration.py, uber/site_sections/reg_admin.py, uber/utils.py
Whatever I did before caused way too many problems, so now we are using the old normalized emails for attendee accounts again. This should hopefully stop creating multiple accounts with different cases.
=> Add old normalization back into attendee accounts

uber/models/commerce.py, uber/payments.py, uber/site_sections/reg_admin.py
This attempts to fix https://jira.furfest.org/projects/SEI_SD/queues/custom/66/SEI_SD-1255 but I'm not sure if it's reproducible with unsettled transactions so I'm leaving some debug logging in.
Also fixes an issue where credits offered a refund button, which makes no sense. Also distinguishes between voids and refunds in the message to admins.
=> Refund-related fixes and debugging

uber/payments.py, uber/site_sections/reg_admin.py, uber/tasks/registration.py, uber/templates/preregistration/attendee_card.html, uber/templates/preregistration/homepage.html, uber/templates/preregistration/stripeForm.html
Fixes the refund buttons on receipts, adds the customer IP to authorize net requests, marks pending badges invalid instead of deleting them, and updates the "Purchased" date on Imported badges to be more clear.
Also, I made some important-to-me changes for the hotel lottery and would have bet money we committed and deployed them and instead they were just sitting on my harddrive, so this adds those even though it's a bit pointless at this point.
=> Various payment and miscellaneous fixes for Registration

uber/api.py
I never updated our API calls when I changed how marketplace apps work, which is now causing all attendee accounts to import as empty accounts. Oops.
=> Fix 500 error when exporting attendees

alembic/versions/94aa84890142_add_unused_years_count_to_attendee_.py, uber/models/__init__.py, uber/models/attendee.py, uber/tasks/registration.py, uber/utils.py
This won't do anything for us immediately, but by keeping track of the number of years an account remains empty we can sunset accounts that haven't been associated with a badge in 2+ years.
=> Count # of years imported accounts are empty

uber/models/attendee.py
For the fix for SEI_SD-1726, we need to be able to set the group name via the attendee. Adding a setter to the event plugin doesn't actually work, so it needs to be done here.
=> Add group name setter

uber/models/attendee.py, uber/models/group.py, uber/site_sections/preregistration.py, uber/templates/group_admin/form.html, uber/templates/preregistration/dealer_group_members.html, uber/templates/preregistration/form.html, uber/templates/preregistration/group_add_members.html, uber/templates/preregistration/group_members.html
Gives group leaders the ability to add existing badges by entering their ID, first name, and last name. This is disabled by default via the "can_add_existing_badges" property -- we're using a DB property rather than a config option as it's likely any event that uses it will want to enable it only for specific kinds of groups.
Also fixes a fairly serious bug where a badge that was not paid for by a group could be unset and then reassigned... yikes. Similarly, badges now can't be unset if they have an admin account or are a department head.
Also also, breaks up the group members template a bit more -- this was originally to allow override via plugin, but I ended up putting the functionality in the main repo since it relies on page handlers.
=> Let groups add existing badges

uber/site_sections/reg_admin.py
When I implemented per-category refunds I failed to account for the fact that the Group model's department changes based on if the group is a dealer or not. Checking the category when refunding may not be the best approach to begin with, but for this year we'll just do a quick fix.
=> Fix dealer refunds being skipped

uber/templates/preregistration/group_members.html
Existing dealer forms weren't being validated at all, which probably explains a lot of past issues.
=> Validate existing group updates

uber/models/attendee.py, uber/templates/forms/macros.html
Fixes a few things needed for MFF to presell one-day badges by adding a selector to the card options for easy access via JS and avoiding treating a one-day badge as equal to an attendee badge in available_badge_type_opts.
=> Support preselling one-day badges

uber/forms/__init__.py, uber/site_sections/preregistration.py, uber/templates/forms/macros.html, uber/templates/group_admin/form.html, uber/templates/preregistration/dealer_registration.html, uber/templates/preregistration/group_members.html
Adds support for file fields to our form macro for WTForms. This macro assumes that you'll have the field data display any uploaded files. Also updates the validation macro so that it can send through files (form.serialize() discards them), and adds file support encoding to the group forms.
=> Add support for dealer file uploads

uber/models/attendee.py, uber/models/hotel.py, uber/templates/confirm_tabs.html, uber/templates/hotel_lottery/room_group.html, uber/templates/hotel_lottery/terms.html
The quick-add function didn't account for the fact that attendees can't enter staff blocks. This should hopefully not be a problem in practice, but the rest of the code accounts for this case so we might as well also do it here.
=> Account for staff/attendee room groups for quick-add room groups

uber/models/attendee.py, uber/payments.py, uber/site_sections/preregistration.py, uber/site_sections/reg_admin.py, uber/tasks/registration.py, uber/templates/reg_admin/receipt_items.html
Updates and improves the way we handle purchaser IDs:
- Fixes a bug where purchaser_id wasn't being assigned in several cases
- Removes the account-based fallback ID, as we consider it acceptable to have invalid purchasers
- Adds controls to allow transferring and merging receipts (the latter being doable by closing an existing receipt, transferring an active receipt, and then moving all the items from the closed receipt to the transferred receipt)
=> Update purchaser logic

uber/site_sections/preregistration.py
Staging is throwing this error when attempting to pay for a registration:
```
Traceback (most recent call last):
File "/app/uber/decorators.py", line 429, in charge
return func(self, session=session, id=id, **kwargs)
File "/app/uber/site_sections/preregistration.py", line 860, in prereg_payment
used_codes[attendee.promo_code_code] += 1
^^^^^^^^^^
NameError: name 'used_codes' is not defined
```
This restores the initialization of `used_codes` removed here: https://github.com/MidwestFurryFandom/rams/commit/7ed7b48c1a934080ee7c7c89555d95d25e00bc96#diff-03575a268e0b3eb2ce5dbf03b98d2f6452807208425701051a48dfe476847b0bL832
=> Restoring initialization of used_codes

uber/site_sections/hotel_lottery.py
We can recover the data involved, but this is definitely a problem we want to fix ASAP.
=> Stop deleting roommate name and cellphone
